"""
Selenium State Reset Tool

This script reads recorded user interaction sessions (JSON files generated by the UsersFirst extension)
and replays them in two modes:
1. ON state: All checkboxes/toggles are set to checked (True)
2. OFF state: All checkboxes/toggles are set to unchecked (False)

This is useful for testing privacy settings and understanding how different toggle states affect website behavior.

How It Works:
- Processes events sequentially as recorded: clicks, changes, keydown, scroll, navigation
- For 'click' events: Finds and clicks the element
- For 'change' events with 'checked' field: Finds element, checks current state, clicks only if state needs to change
- For 'change' events with 'value' field: Sets text input values
- When set_checked_state is specified, all toggles are forced to that state (ON/OFF mode)

Click Methods (with automatic fallback):
The script tries multiple click methods to handle stubborn elements (React Material-UI, custom toggles, etc.):
1. Standard Selenium click() - works for most elements
2. JavaScript click() - bypasses visibility/interactability checks, good for React components
3. ActionChains click() - simulates actual mouse movement and click
This ensures clicks work even on complex React/Angular components with custom event handlers.

Element Finding Strategy:
The script uses semantic information captured by the extension to reliably find elements even when
DOM structure changes (e.g., React components with random IDs). Priority order:
1. data-testid, data-cy, data-automation (most stable)
2. id attribute
3. name attribute (for form inputs)
4. aria-label
5. label text matching
6. CSS selector (position-based)
7. XPath (last resort)

Usage (run from the repository root):
    # Replay a shipped (templatized) trace -- substitutes {{WEBSP_ACCOUNT_*}} from .env
    python src/state_reset_check.py --templatized_trace \
        --session_json dataset/state_traces/Wolfram_task-7/<session-folder>/session-<...>.json

    # Only ON or only OFF
    python src/state_reset_check.py --templatized_trace --state_mode on --session_json <path>

    # Replay your own (non-templatized) recording
    python src/state_reset_check.py --session_json path/to/your/session-<...>.json
"""

from pathlib import Path
import argparse
import shutil
import os
import json
import time

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# The replay engine is shared with the agent (src/state_reset/extension_reset.py); import
# replay_events instead of duplicating the locator/replay logic here. The agent's
# load_json_file (imported as load_json_file_templatized) also substitutes the
# {{WEBSP_ACCOUNT_*}} placeholders from .env -- used when --templatized_trace is set.
from state_reset.extension_reset import replay_events, load_json_file as load_json_file_templatized


def load_json_file(json_file):
    with open(json_file, 'r', encoding='utf-8') as f:
        return json.load(f)


parser = argparse.ArgumentParser()
parser.add_argument("--session_json", type=str, required=True,
help="Path (absolute or relative to the repo root) to the recorded session-*.json trace to replay.")
parser.add_argument("--test_profile_dir_name", type=str, default="test_profile")
parser.add_argument("--google_signin", action='store_true')
parser.add_argument("--use_extension", action='store_true')
parser.add_argument("--default_download_dir", type=str, default="~/Downloads",
help="Default download directory for the browser. Use this if you want to save the files during the clicks to a specific directory.")
parser.add_argument("--state_mode", type=str, default="both", choices=["on", "off", "both"],
help="Which state(s) to run: 'on' (only ON state), 'off' (only OFF state), or 'both' (default)")
parser.add_argument("--templatized_trace", action='store_true',
help="Substitute {{WEBSP_ACCOUNT_*}} placeholders from .env before replay. Use for the shipped dataset/state_traces; omit for your own recordings.")
parser.add_argument("--skip_disabled_clicks", action='store_true',
help="Skip clicking on disabled buttons/elements during replay. Checks for disabled attribute, aria-disabled, and disabled classes.")

args = parser.parse_args()

PARENT_DIR = Path(__file__).parent
test_profile_dir_name = args.test_profile_dir_name
print(f"Using test profile directory: {test_profile_dir_name}")

profile_dir = PARENT_DIR / test_profile_dir_name

#Override the profile directory if google signin is enabled
if args.google_signin:
    #Create a temp profile directory copied from `test_profile_just_google_signed_on` directory
    profile_dir = PARENT_DIR / 'temp_profile_just_google_signed_on' 
    if os.path.exists(profile_dir):
        shutil.rmtree(profile_dir) #If it already exists, delete it and copy from the original
    shutil.copytree(PARENT_DIR / 'test_profile_just_google_signed_on', profile_dir)
print(f"Using profile directory: {profile_dir}")

# the user passes the path to a single recorded session-*.json trace
json_clicks_file = args.session_json
if not os.path.isfile(json_clicks_file):
    raise ValueError(f"Session JSON file {json_clicks_file} does not exist")
print(f"Processing session: {json_clicks_file}")
load_trace = load_json_file_templatized if args.templatized_trace else load_json_file
clicks_data = load_trace(json_clicks_file)
url = clicks_data.get('startUrl')
viewportWidth = clicks_data.get('viewportWidth', 1280)
viewportHeight = clicks_data.get('viewportHeight', 1024)
events = clicks_data.get('events', [])

if not url:
    raise ValueError("No startUrl found in the session JSON file")

print(f"Start URL: {url}")
print(f"Viewport: {viewportWidth}x{viewportHeight}")
print(f"Total events: {len(events)}")

# Create a fresh options object for this session with the correct viewport size
session_options = Options()

session_options.enable_bidi = True
session_options.enable_webextensions = True

session_options.add_argument(f'--user-data-dir={profile_dir}')
session_options.add_argument("--disable-dev-shm-usage")
session_options.add_argument("--disable-gpu")
session_options.add_argument(f"--window-size={viewportWidth},{viewportHeight}")
session_options.add_argument("--force-device-scale-factor=1")
session_options.add_experimental_option("excludeSwitches", ['enable-automation', 'enable-logging'])
session_options.add_experimental_option('useAutomationExtension', False)
session_options.add_argument('--disable-blink-features=AutomationControlled')
session_options.add_argument('--disable-infobars')
session_options.add_argument('--start-maximized')

ext_dir = None
if not args.use_extension:
    session_options.add_argument('--disable-extensions')
else:
    # ext_dir = Path(__file__).parent / 'UsersFirst-annotation' / 'extension' / 'extension'
    ext_dir = Path(__file__).parent / 'UsersFirst-annotation_v3'
    session_options.add_argument(f'--load-extension={ext_dir}')

session_options.add_argument('--no-sandbox')
session_options.add_argument("--disable-features=DisableLoadExtensionCommandLineSwitch")
session_options.add_argument('--disable-application-cache')
session_options.add_argument('--disable-setuid-sandbox')
session_options.add_argument('--disable-dev-shm-usage')
session_options.add_experimental_option('prefs', {
    "extensions.ui.developer_mode": True,
    'profile.default_content_setting_values.notifications': 5,
    'credentials_enable_service': True,
    'profile.password_manager_enabled': True,
    "plugins.always_open_pdf_externally": True,
    "download.default_directory": args.default_download_dir,
    "download.prompt_for_download": False,
    "download.directory_upgrade": True,
    "safebrowsing.enabled": True
})

# ==================================================================================
# PART 1: Navigate to the page and replay events with elements clicked to ON state
# ==================================================================================
if args.state_mode in ["on", "both"]:
    print(f"\n{'─'*80}")
    print("PART 1: Setting all toggle elements to ON (checked state)")
    print(f"{'─'*80}")
    
    service_on = Service(executable_path=ChromeDriverManager().install())
    driver_on = webdriver.Chrome(options=session_options, service=service_on)
    if ext_dir:
        extension_result = driver_on.webextension.install(path=str(ext_dir))
        print(extension_result)

    try:
        driver_on.get(url)
        driver_on.refresh()
        print(f"Navigated to: {url}")
        time.sleep(2)  # Wait for page to load
        
        # Replay events with checkboxes set to ON (checked=True)
        replay_events(driver_on, events, set_checked_state=True, skip_disabled_clicks=args.skip_disabled_clicks)
        
        print("\n✓ All elements set to ON state")
        print("Waiting 10 seconds to observe the state...")
        time.sleep(10)
        
    except Exception as e:
        print(f"Error during ON state replay: {e}")
    finally:
        driver_on.quit()
        print("Browser closed for ON state")

# ==================================================================================
# PART 2: Navigate to the page and replay events with elements clicked to OFF state
# ==================================================================================
if args.state_mode in ["off", "both"]:
    print(f"\n{'─'*80}")
    print("PART 2: Setting all toggle elements to OFF (unchecked state)")
    print(f"{'─'*80}")
    
    service_off = Service(executable_path=ChromeDriverManager().install())
    driver_off = webdriver.Chrome(options=session_options, service=service_off)
    if ext_dir:
        extension_result = driver_off.webextension.install(path=str(ext_dir))
        print(extension_result)

    try:
        driver_off.get(url)
        print(f"Navigated to: {url}")
        time.sleep(2)  # Wait for page to load
        
        # Replay events with checkboxes set to OFF (checked=False)
        replay_events(driver_off, events, set_checked_state=False, skip_disabled_clicks=args.skip_disabled_clicks)
        
        print("\n✓ All elements set to OFF state")
        print("Waiting 10 seconds to observe the state...")
        time.sleep(10)
        
    except Exception as e:
        print(f"Error during OFF state replay: {e}")
    finally:
        driver_off.quit()
        print("Browser closed for OFF state")

print(f"\n{'='*80}")
print(f"Completed processing session: {json_clicks_file}")
print(f"{'='*80}\n")
